import React from 'react';
import PlaceholderView from '../_PlaceholderView';

/**
 * OutputsView - Browse artifacts and generated files
 *
 * TODO: Implement artifact gallery with:
 * - Image thumbnails with lightbox
 * - File type filtering
 * - Session/cascade grouping
 * - Download and share options
 */
const OutputsView = ({ navigate }) => {
  return (
    <PlaceholderView
      icon="mdi:folder-image"
      title="Outputs"
      description="Browse images, files, and artifacts generated by your cascades. View, download, and organize outputs by session or type."
    />
  );
};

export default OutputsView;
