cascade_id: multi_model_pareto_2
cells:
  - candidates:
      evaluator_instructions: Evaluate the quality of each response for clarity, accuracy, and usefulness.
      factor: 3
      models:
        bytedance-seed/seed-1.6-flash:
          factor: 3
        google/gemini-3-flash-preview:
          factor: 3
        qwen/qwen3-coder-flash:
          factor: 3
        xiaomi/mimo-v2-flash:free:
          factor: 3
      mutate: false
      pareto_frontier:
        enabled: true
        include_dominated: true
        policy: balanced
        quality_metric: evaluator_score
        show_frontier: true
    instructions: 'Complete this task: {{ input.task }}'
    name: generate
    traits:
      - manifest
description: Phase 3 Multi-Model Soundings - Pareto frontier analysis for optimal cost/quality tradeoff
inputs_schema:
  task: The task to complete with Pareto optimization
