-- SAP HANA Sample Data for LARS SQL Connections Testing
-- This script creates tables matching the schema used in other test databases
-- Run with: hdbsql -i 90 -u SYSTEM -p HanaTest1! -d HXE -I 01-sample-data.sql

-- Customers table
CREATE TABLE CUSTOMERS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL,
    CITY NVARCHAR(100),
    COUNTRY NVARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Products table
CREATE TABLE PRODUCTS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME NVARCHAR(200) NOT NULL,
    CATEGORY NVARCHAR(100),
    PRICE DECIMAL(10, 2) NOT NULL,
    STOCK_QUANTITY INTEGER DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Orders table
CREATE TABLE ORDERS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS NVARCHAR(50) DEFAULT 'pending',
    TOTAL_AMOUNT DECIMAL(12, 2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

-- Order items table
CREATE TABLE ORDER_ITEMS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORDER_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

-- Support tickets table
CREATE TABLE SUPPORT_TICKETS (
    ID INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    SUBJECT NVARCHAR(255) NOT NULL,
    DESCRIPTION NCLOB,
    PRIORITY NVARCHAR(20) DEFAULT 'medium',
    STATUS NVARCHAR(50) DEFAULT 'open',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESOLVED_AT TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

-- Insert sample customers
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('Alice Johnson', 'alice@example.com', 'New York', 'USA');
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('Bob Smith', 'bob@example.com', 'Los Angeles', 'USA');
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('Carol Williams', 'carol@example.com', 'Chicago', 'USA');
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('David Brown', 'david@example.com', 'Houston', 'USA');
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('Eva Martinez', 'eva@example.com', 'Phoenix', 'USA');
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('Frank Garcia', 'frank@example.com', 'Toronto', 'Canada');
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('Grace Lee', 'grace@example.com', 'Vancouver', 'Canada');
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('Henry Wilson', 'henry@example.com', 'London', 'UK');
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('Ivy Taylor', 'ivy@example.com', 'Manchester', 'UK');
INSERT INTO CUSTOMERS (NAME, EMAIL, CITY, COUNTRY) VALUES ('Jack Anderson', 'jack@example.com', 'Sydney', 'Australia');

-- Insert sample products
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('Laptop Pro 15', 'Electronics', 1299.99, 50);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('Wireless Mouse', 'Electronics', 29.99, 200);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('USB-C Hub', 'Electronics', 49.99, 150);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('Mechanical Keyboard', 'Electronics', 149.99, 75);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('Monitor 27 inch', 'Electronics', 399.99, 30);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('Office Chair', 'Furniture', 299.99, 25);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('Standing Desk', 'Furniture', 599.99, 15);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('Desk Lamp', 'Furniture', 39.99, 100);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('Notebook Set', 'Office Supplies', 12.99, 500);
INSERT INTO PRODUCTS (NAME, CATEGORY, PRICE, STOCK_QUANTITY) VALUES ('Pen Pack', 'Office Supplies', 8.99, 1000);

-- Insert sample orders
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (1, 'completed', 1349.98);
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (2, 'completed', 449.98);
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (3, 'pending', 599.99);
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (1, 'shipped', 179.98);
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (4, 'completed', 1299.99);
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (5, 'pending', 339.98);
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (6, 'completed', 49.99);
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (7, 'shipped', 899.98);
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (8, 'completed', 21.98);
INSERT INTO ORDERS (CUSTOMER_ID, STATUS, TOTAL_AMOUNT) VALUES (9, 'pending', 149.99);

-- Insert sample order items
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (1, 1, 1, 1299.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (1, 2, 1, 29.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (1, 3, 1, 49.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (2, 5, 1, 399.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (2, 3, 1, 49.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (3, 7, 1, 599.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (4, 4, 1, 149.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (4, 2, 1, 29.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (5, 1, 1, 1299.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (6, 6, 1, 299.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (6, 8, 1, 39.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (7, 3, 1, 49.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (8, 7, 1, 599.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (8, 6, 1, 299.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (9, 9, 1, 12.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (9, 10, 1, 8.99);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE) VALUES (10, 4, 1, 149.99);

-- Insert sample support tickets
INSERT INTO SUPPORT_TICKETS (CUSTOMER_ID, SUBJECT, DESCRIPTION, PRIORITY, STATUS) VALUES (1, 'Laptop not charging', 'My new laptop stopped charging after 2 weeks of use.', 'high', 'open');
INSERT INTO SUPPORT_TICKETS (CUSTOMER_ID, SUBJECT, DESCRIPTION, PRIORITY, STATUS) VALUES (2, 'Wrong item received', 'I ordered a keyboard but received a mouse instead.', 'medium', 'resolved');
INSERT INTO SUPPORT_TICKETS (CUSTOMER_ID, SUBJECT, DESCRIPTION, PRIORITY, STATUS) VALUES (3, 'Shipping delay inquiry', 'My order has been pending for 5 days. When will it ship?', 'low', 'open');
INSERT INTO SUPPORT_TICKETS (CUSTOMER_ID, SUBJECT, DESCRIPTION, PRIORITY, STATUS) VALUES (4, 'Return request', 'I would like to return the monitor as it has dead pixels.', 'high', 'in_progress');
INSERT INTO SUPPORT_TICKETS (CUSTOMER_ID, SUBJECT, DESCRIPTION, PRIORITY, STATUS) VALUES (5, 'Product question', 'Does the standing desk come with assembly instructions?', 'low', 'resolved');

COMMIT;
